import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LizBoutique - Dashboard",
  description: "Generated by bb Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
